### ISSUE TITLE
Feature: Enable "Releases" in Repository

### ISSUE THREAD

**Issue by seangwright** [Kentico/xperience-algolia#14]
### Motivation

Currently, there's no way to easily tell what is being released with each new version of this library.

The Xperience docs [have release notes](https://docs.xperience.io/release-notes-xperience-13) and we even have notes [for hotfixes](https://devnet.kentico.com/download/hotfixes).

### Proposed solution

Enable and author [releases](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases) for this repository so developers can know what changes have been added with each version of the library.

### Additional context

Example of [a repository](https://github.com/wiredviews/xperience-page-builder-utilities/releases) using releases.

**Comment by kentico-ericd** [comment]
Releases have been enabled 👍
