### ISSUE TITLE
Feature: Processing Large Documents in Chunks

### ISSUE THREAD

**Issue by seangwright** [Kentico/xperience-algolia#19]
### Motivation

Algolia's documentation recommends [breaking up large documents into chunks](https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/how-to/indexing-long-documents/) for better search relevancy of results and also to prevent hitting the [search record size limit](https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/how-to/reducing-object-size/) for a plan.

If we use the Xperience crawler for a page, crack a PDF, or have many structured content fields with blocks of text, we might want to chunk this content into multiple records.

Currently, this library creates 1 Algolia search record for each Page in the Content Tree, so chunking would have to a fully custom solution outside of this integration.

### Proposed solution

I'm not sure the best way to introduce this feature at the moment, but my initial idea would be to start where the `JObject` [is created from the page's content](https://github.com/Kentico/xperience-algolia/blob/master/src/Services/Implementations/DefaultAlgoliaIndexingService.cs#L77).

This could be changed to `IList<JObject>` and then have everything that populates this collection be updated to work with sets/lists instead of single items.

Or, it might be better to add a new indexing attribute to indicate a field should be chunked and then provide a method for creating the chunks.

### Additional context

This would also require configuring an [attribute for distinct](https://www.algolia.com/doc/api-reference/api-parameters/attributeForDistinct/) for the index.

**Comment by kentico-ericd** [comment]
@seangwright I've pushed a potential solution for this in https://github.com/Kentico/xperience-algolia/pull/26. Can you please take a look and provide some feedback?

**Comment by seangwright** [comment]
Thanks! Yup - I'll take a look on Thursday when I'm back to working on the site using Algolia.
