### ISSUE TITLE
Documents under workflow aren't handled if the document is moved in the tree

### ISSUE THREAD

**Issue by jkerb135** [Kentico/xperience-algolia#33]
When moving documents in the Tree the event triggered is "DocumentEvents.Update" if this page is under workflow the task will be skipped in the DefaultAlgoliaTaskLogger.

```
if ((eventName.Equals(DocumentEvents.Insert.Name, StringComparison.OrdinalIgnoreCase) || eventName.Equals(DocumentEvents.Update.Name, StringComparison.OrdinalIgnoreCase)) && node.GetWorkflow() != null)
 {
      // Do not handle Insert/Update for pages under workflow
      return;
 }
```

This will cause the indexed data to become invalid if there are path specific values built using the parents nodeid or path.

A workaround I have implemented in a custom module to force send the task on update with the event name of publish if the changed columns contain "NodeParentID"

```
DocumentEvents.Update.Before += ForceMoveUpdate

 private void ForceMoveUpdate(object sender, DocumentEventArgs e)
    {
        var columns = e.Node.ChangedColumns();
        if (columns.Any(col => col.Equals(nameof(TreeNode.NodeParentID), StringComparison.OrdinalIgnoreCase)))
        {
            algoliaTaskLogger.HandleEvent(e.Node, WorkflowEvents.Publish.Name);
        }
    }
```

**Comment by ondrejhenek** [comment]
Hi! Thanks for sharing your problem and a solution! We'll take a look at it soon and consider adding it to the original integration.

**Comment by bkapustik** [comment]
Hello, this workaround has been implemented in the following pull request.
https://github.com/Kentico/xperience-algolia/pull/34
